services:
  - type: web
    name: evai-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build && npm install -g serve
    startCommand: cd frontend && serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com # Placeholder

  - type: web
    name: evai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_KEY
        value: your_actual_api_key_to_be_set_in_render # Placeholder
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-url.onrender.com # Placeholder for the deployed frontend URL