services:
  - type: web
    name: evai-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build && npm install -g serve
    startCommand: cd frontend && serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0

  - type: web
    name: evai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 